package info.isaksson.erland.whiteboard.security;

public enum BoardCapability {
    BOARD_READ,
    BOARD_WRITE,
    BOARD_OWNER,
    FACILITATE_BOARD,
    PUBLICATION_READ,
    COMMENT_PARTICIPATE,
    VOTE_PARTICIPATE,
    VOTE_OBSERVE,
    TIMER_CONTROL,
    TIMER_OBSERVE,
    REACTION_EMIT,
    REACTION_OBSERVE,
    PRIVATE_MODE_CONTRIBUTE,
    PRIVATE_MODE_REVEAL,
    PRIVATE_MODE_VIEW,
    ASSET_USE,
    ASSET_MANAGE,
    LIBRARY_READ,
    LIBRARY_SHARE,
    LIBRARY_MANAGE
}
